---
x-nautobot-build: &nautobot-build
  build:
    args:
      NAUTOBOT_VER: "${NAUTOBOT_VER}"
      PYTHON_VER: "${PYTHON_VER}"
    context: "../"
    dockerfile: "development/Dockerfile"
x-nautobot-base: &nautobot-base
  image: "nautobot-floor-plan/nautobot:${NAUTOBOT_VER}-py${PYTHON_VER}"
  env_file:
    - "development.env"
    - "creds.env"
  tty: true

services:
  nautobot:
    depends_on:
      redis:
        condition: "service_started"
      db:
        condition: "service_healthy"
      selenium:
        condition: "service_started"
    <<:
      - *nautobot-base
      - *nautobot-build
  worker:
    entrypoint:
      - "sh"
      - "-c"  # this is to evaluate the $NAUTOBOT_LOG_LEVEL from the env
      - "nautobot-server celery worker -l $$NAUTOBOT_LOG_LEVEL --events"  ## $$ because of docker-compose
    depends_on:
      nautobot:
        condition: "service_healthy"
    healthcheck:
      interval: "30s"
      timeout: "10s"
      start_period: "30s"
      retries: 3
      test: ["CMD", "bash", "-c", "nautobot-server celery inspect ping --destination celery@$$HOSTNAME"]  ## $$ because of docker-compose
    <<: *nautobot-base
  beat:
    entrypoint:
      - "sh"
      - "-c"  # this is to evaluate the $NAUTOBOT_BEAT_LOG_LEVEL from the env
      - "nautobot-server celery beat -l $$NAUTOBOT_BEAT_LOG_LEVEL"  ## $$ because of docker-compose
    depends_on:
      nautobot:
        condition: "service_healthy"
    healthcheck:
      disable: true
    <<: *nautobot-base
  selenium:
    image: "selenium/standalone-firefox:4.27"
    ports:
      - "4444"
      - "5900"
    shm_size: "2g"
