# Generated by Django 3.2.16 on 2022-12-07 05:11

import django.core.serializers.json
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0053_relationship_required_on"),
        ("nautobot_floor_plan", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="floorplan",
            name="_custom_field_data",
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name="floorplan",
            name="tags",
            field=taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag"),
        ),
    ]
