# Generated by Django 3.2.21 on 2024-03-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_floor_plan", "0003_auto_20230908_1339"),
    ]

    operations = [
        migrations.AddField(
            model_name="floorplan",
            name="x_axis_labels",
            field=models.CharField(default="numbers", max_length=10),
        ),
        migrations.AddField(
            model_name="floorplan",
            name="y_axis_labels",
            field=models.CharField(default="numbers", max_length=10),
        ),
    ]
