# Generated by Django 3.2.25 on 2024-07-19 22:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_floor_plan', '0005_add_rackgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='x_origin_seed',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='y_origin_seed',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
