# Generated by Django 4.2.19 on 2025-02-25 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0067_controllermanageddevicegroup_tenant"),
        ("nautobot_floor_plan", "0009_add_custom_label_support"),
    ]

    operations = [
        migrations.RenameField(
            model_name="floorplantile",
            old_name="rack_orientation",
            new_name="object_orientation",
        ),
        migrations.AddField(
            model_name="floorplantile",
            name="device",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="floor_plan_tile",
                to="dcim.device",
            ),
        ),
        migrations.AddField(
            model_name="floorplantile",
            name="power_feed",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="floor_plan_tile",
                to="dcim.powerfeed",
            ),
        ),
        migrations.AddField(
            model_name="floorplantile",
            name="power_panel",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="floor_plan_tile",
                to="dcim.powerpanel",
            ),
        ),
    ]
